# Sample configuration file for LAFS data generation

# Output info
num_items = 1000
initial_list_size = 200
recommendation_size = 50
num_users_per_propensity= [100,100]

# Matrix info
num_factors = 10
std_dev_factors = 1.0

# User and item generation info
user_feature_propensities = [[[0.9, 0.1],[0.1, 0.1],[0.1, 0.1], [0.3, 1.0],[0.6, 1.0],[0.1, 0.6], [0.4, 1.0],[0.9, 1.0],[0.1, 0.6], [0.0, 1.0]],
                    [[0.5, 0.5],[0.5, 0.5],[0.5, 0.5], [0.3, 1.0],[0.6, 1.0],[0.1, 0.6], [0.4, 1.0],[0.9, 1.0],[0.1, 0.6], [0.0, 1.0]]]
item_feature_propensities = [0.1, 0.3, 0.9, 0.5, 0.6, 0.2, 0.5, 0.7, 0.6, 0.1]

# Fairness info
num_sensitive_features = 3
feature_bias = [[0.5, 0.1], [0.0, 0.0], [0.0, 0.0]]

# Output files
compatibilities_file = "data/sample_compatibilities.csv"
item_features_file = "data/sample_item_features.csv"
user_factors_file = "data/sample_user_factors.csv"
item_factors_file = "data/sample_item_factors.csv"
ratings_file = "data/sample_ratings.csv"
